Feature/#2 company table
2-ViewMyStartup-2-FE/2-ViewMystartup-2team-BE pull request #3
Opened 2024-09-26 04:01 UTC by annylee0723

2024-09-26 13:14 UTC, taeyeonkim94 requested changes

2024-09-26 13:14 UTC, taeyeonkim94 commented on prisma/schema.prisma
> +  logoImage             String[]
로고이미지는 이미지가 하나만 들어가는데 배열일 필요가 있을까요?

2024-09-26 13:14 UTC, taeyeonkim94 commented on prisma/schema.prisma
> +  myChosenCount         Int
myChosenCount, comparedChosenCount 는 지금 처럼 mock 데이터인 경우에는 상관이 없지만
데이터 생성시에는 입력을 받는게 아닌 입력을 받아서 생성시에 디폴트값으로 0을 만드는게 맞지 않을까요?

2024-09-27 00:30 UTC, annylee0723 commented on prisma/schema.prisma
> +  logoImage             String[]
solve: 문자열로 수정 후 기본 값 설정
as-is: `String[]`
tobe: `String @default("")`

2024-09-27 00:33 UTC, annylee0723 commented on prisma/schema.prisma
> +  myChosenCount         Int
solve: actualInvestAmount, simulatedInvestAmount, myChosenCount, comparedChosenCount > default값 지정
as-is: `@default` 값 없었음
tobe: @default(0)

2024-09-27 00:40 UTC, merged