Count get api 생성
2-ViewMyStartup-2-FE/2-ViewMystartup-2team-BE pull request #6
Opened 2024-09-26 07:19 UTC by annylee0723

## #4 Count get api 생성
- #4 

## 작업 사항
- 비교 현황 페이지 내 사용될 get api 생성
 - API endpoint 설정 (/api/companies/counts )
 - Count Route 생성
 - Count Controller 생성(비지니스 로직 생성)
 - App.js에 추가
 - http 테스트 파일 생성

2024-09-26 13:13 UTC, taeyeonkim94 requested changes

2024-09-26 13:13 UTC, taeyeonkim94 commented on controllers/countController.js
> +  let orderBy;
저 같은 경우에는 let으로 선언하는거 보다는 const로 선언해서 삼항연산자를 이용합니다
const orderBy = 
  order === "myCountHighest" ?  { myChosenCount: "desc" } : 
  order === "myCountLowest" ? {myChosenCount: "asc"} : ...//
이런식으로요 정보공유입니다.

2024-09-26 13:13 UTC, taeyeonkim94 commented on controllers/countController.js
> +  const parsedPage = Number(page) > 0 ? Number(page) : 1;
변수명은 pasredPage 인데 결과값은 Number(page) 네요
현 상황에서는 문제가 생기지 않겠지만 일치하면 좋을거같아요.

2024-09-26 13:13 UTC, taeyeonkim94 commented on prisma/schema.prisma
> +  myChosenCount         Int
여기도 simulatedInvestAmount와 myChosenCount는 디폴트값을 주는게 좋아보여요 이미지도 배열이 아니라 스트링이 좋아보여요

2024-09-26 13:13 UTC, taeyeonkim94 commented on prisma/seed.js
> +    data: COMPANIES,
시드파일에 딜리트 메소드까지 추가해서 데이터를 초기화가 됐으면 좋겠어요

2024-09-26 23:58 UTC, annylee0723 commented on prisma/seed.js
> +    data: COMPANIES,
딜리트 메소드는 필요한 사람이 추가해서 쓰지 않을까 싶어서 작성 안했는데 작성 할까욥??

2024-09-27 00:42 UTC, taeyeonkim94 commented on prisma/seed.js
> +    data: COMPANIES,
현 상황에서 꼭 필요한 기능은 아니다보니 이대로 넣어도 상관 없을거 같네요

2024-09-27 01:10 UTC, annylee0723 commented on controllers/countController.js
> +  let orderBy;
꿀팁 감사합니다.. JS 무궁무진 하네요ㅋㅋㅋㅋ
solve: 
as-is: switch문
to-be: 삼항연산

2024-09-27 01:14 UTC, annylee0723 commented on prisma/schema.prisma
> +  myChosenCount         Int
#3 에서 해결 완

2024-09-27 01:17 UTC, annylee0723 commented on controllers/countController.js
> +  const parsedPage = Number(page) > 0 ? Number(page) : 1;
파라미터명이랑 변수명이랑 겹치는걸 선호하지 않아서 분리해뒀습니다. 근데 말씀 주신것 처럼 변수명이 직관적이지 않은것 같아서 pageNum으로 수정했습니다!(하는 김에 Limit도 얼라인 맞추는 겸 수정했슴다)
solve: 변수명 수정
as-is: parsedPage, parsedLimit
to-be: pageNum, limitNum

2024-09-27 01:17 UTC, annylee0723 commented on prisma/seed.js
> +    data: COMPANIES,
넵!

2024-09-27 01:47 UTC, taeyeonkim94 approved these changes

2024-09-27 01:47 UTC, merged